[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_contract = "EbbermosrWwxzWb3R4LmiXsXvdHV1JEkYr1e3mwDWjQv"
nft_contract = "7mEjdqGfFBtH3T6qWHBxTLwq2PoaYjZjr4zF2w8kZ5FY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nft-contract.ts"
test-staking= "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking-contract.ts"

[workspace]
members = [
  "programs/staking-contract",
  "programs/nft-contract"
]