apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stakeit
  namespace: stakeit
spec:
  secretName: stakeit-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: stakeIT.krishdev.xyz
  dnsNames:
  - stakeIT.krishdev.xyz